### ISSUE TITLE
Ampliar limite do tamanho de upload na Mediawiki

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/wiki-backup#1]
![image](https://user-images.githubusercontent.com/1651447/233635259-a3481e00-15a6-4342-806a-eda0c9a8dd6f.png). 

Eventualmente será preciso ampliar também no PHP,  **40 Mb** é um aumento razoável. É uma demanda [comum em diversos content managers](https://www.drupal.org/docs/7/managing-site-performance-and-scalability/increase-upload-size-in-your-phpini). Para imagens unitárias inclusive mapas em PNG (não avaliei arquivos PDF) é suficiente. Ver https://stackoverflow.com/a/2184541/287948

Estamos usando a Mediawiki de fonte das imagens originais, muitas delas requerem boa resolução. Posteriormente com hospedagem em nuvem podemos configurar o PHP e o NGNIX para associar path de imagens a outro servidor, e manter no principal apenas os thumbs e as imagens menores.

**Comment by crebollobr** [comment]
Coloquei 100Mb se precisar podemos aumentar

**Comment by IgorEliezer** [comment]
@crebollobr resolveu e confirmo.

https://wiki.addressforall.org/doc/Arquivo:Dg-postgis_remote_in_qgis2.png
