### ISSUE TITLE
Instalar Scribunto

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/wiki-backup#10]
A maior parte dos *templates* da Wikipedia oficial da lingua inglesa está codificada em Scribunto... Desde um simples [template:main](https://en.wikipedia.org/wiki/Template:Main) (ex. [esse invoke](https://en.wikipedia.org/w/index.php?title=Module:Labelled_list_hatnote&action=edit)), até os infoboxes mais complexos. Todos fazem uso dessa *extension*:
https://www.mediawiki.org/wiki/Extension:Scribunto

É portanto recomendável seguirmos a mesma boa prática dentro da nossa Wiki.

PS: aguardar passagem para o novo servidor.

**Comment by crebollobr** [comment]
Unificar as issues 
https://github.com/AddressForAll/wiki-backup/issues/7
