### ISSUE TITLE
A Wiki não mais acessa imagens do Commons

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/wiki-backup#13]
A Wiki não mais acessa imagens do Commons.

Exemplos:
* https://wiki.addressforall.org/doc/Predefini%C3%A7%C3%A3o:Aviso - imagem quebrada dentro do box laranja.
* https://wiki.addressforall.org/doc/Documenta%C3%A7%C3%A3o_Digital-guard#Se%C3%A7%C3%B5es - imagens de progresso/stage.

Verificar se no LocalSettings.php o [`$wgUseInstantCommons`](https://www.mediawiki.org/wiki/Manual:$wgUseInstantCommons) está `true`. ([original](https://github.com/AddressForAll/wiki-backup/blob/main/src/LocalSettings.php#L84C29-L84C29))

**Comment by crebollobr** [comment]
Feito
https://github.com/AddressForAll/WS/issues/19#issuecomment-1731353415
