### ISSUE TITLE
Clone da Wiki onde deletaremos o que não queremos revelar.

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/wiki-backup#14]
No Clone, vamos criar o login para entrar. wikifull.addressforall.org. Vamos aproveitar para colocar esta wikifull no Oracle.
Na Wiki atual vamos deletar as partes confidenciais. wiki.addressforall.org

**Comment by crebollobr** [comment]
wikifull criada mas com problema nas imagens importadas
sem log no debug 
foi importada novamente as imagens com problema e funcionou

**Comment by crebollobr** [comment]
Hoje funcionou as imagens, sem nenhuma intervenção
