### ISSUE TITLE
Syntaxhighlight falhando novamente

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/wiki-backup#3]
Instalação atual da Mediawiki falhando novamente.

Arrumar syntaxhighlight e testar pelo menos para  Python e Bash, exemplos abaixo.

```
<syntaxhighlight lang="python">
def quick_sort(arr):
    less = []
    pivot_list = []
    more = []
    if len(arr) <= 1:
        return arr
</syntaxhighlight>

<syntaxhighlight lang="bash">
pandoc -f commonmark markdownfile.md -t mediawiki -o out.wiki
pandoc -t mediawiki -f html  SBIDE2022resumo1osmCodesMetodologia.html  # = SPans e divs
pandoc -f html -t markdown-raw_html-native_divs-native_spans SBIDE2022resumo1osmCodesMetodologia.html
</syntaxhighlight>
```

**Comment by crebollobr** [comment]
por favor testar novamente

**Comment by IgorEliezer** [comment]
@ppKrauss, falta o parâmetro 'line' na 1ª linha.

`<syntaxhighlight lang="python" line>`

Teste e vê se sua página sai da categoria de erro no syntaxhighlight https://wiki.addressforall.org/doc/Categoria:P%C3%A1ginas_com_erros_de_realce_de_sintaxe.

**Comment by crebollobr** [comment]
se tiver mais problema com esse plugin, reabrir a issue

**Comment by IgorEliezer** [comment]
Parece que está funcionando: https://wiki.addressforall.org/doc/Sandbox#Bloco_de_c%C3%B3digo
