### ISSUE TITLE
Instalar a extensão Mermaid 

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/wiki-backup#4]
A wiki está precisando da extensão Mermaid para renderizar esquemas que foram importados dos docs no GitHub para a wiki.

### Exemplo

Um esquema como o abaixo:

```mermaid
classDiagram
    Jurisdiction *-- "0..1" Jurisdiction_geom
    Donated_PackTpl "0..1" -->  Jurisdiction: has scope
    Donated_PackTpl "*" --> Donor: has
    Donor "0..1" ..> Jurisdiction: has agg scope

    class Jurisdiction { osm_id bigint }
    class Jurisdiction_geom { osm_id bigint }
    class Donor {
      id integer
      scope_osm_id bigint
    }
    class Donated_PackTpl {
        id integer
        scope_osm_id bigint
        donor_id integer
    }
```

... renderiza como bloco de código, como se pode ver em https://wiki.addressforall.org/doc/Sandbox#Esquemas.

Extensão disponível em: https://www.mediawiki.org/wiki/Extension:Mermaid

Outros exemplos: https://github.com/digital-guard/preserv/blob/main/docs/pt/specUML.md#donated_packtpl-e-jurisdiction

**Comment by crebollobr** [comment]
Foi instalado,
https://wiki.addressforall.org/doc/Teste.
Não sei se tem relação mas o sandbox parou de funcinar

**Comment by crebollobr** [comment]
realmente o prugin altera alguma coisa no sandbox que trava o php

**Comment by crebollobr** [comment]
refiz o processo e está ok

**Comment by crebollobr** [comment]
deu problema em outros sites

**Comment by crebollobr** [comment]
acho que é o php

**Comment by IgorEliezer** [comment]
> acho que é o php

@crebollobr, então não funciona ou só precisamos mudar a configuração/versão do php do wiki?

**Comment by crebollobr** [comment]
Fiz a mudança do PHP, mas quebra o site em outros pontos.
Uma possibilidade é refazer todo o site com o php antigo. Mas demora muito tempo.

**Comment by crebollobr** [comment]
Não compatível

**Comment by IgorEliezer** [comment]
Ok, então como workaround podemos dar print e gerar imagens, e o código deixar salvo em algum lugar como comentário.
