### ISSUE TITLE
SVG da Wikipedia mal renderizada 

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/wiki-backup#5]
Imagem SVG da Wikipedia não está sendo renderizada corretamente: parece ser bug da Mediawiki mesmo.

Exemplo: ao usar `[[File:Reverse proxy h2g2bob.svg|thumb]]`  **não renderizou o texto**, apenas as geometrias.

Ver https://en.wikipedia.org/wiki/File:Reverse_proxy_h2g2bob.svg

------

Sugestões de teste e discussão:

1. Testar com arquivos SVG locais. 
2. Postar pergunta no Stackoverflow e nas discussões Mediawiki

**Comment by crebollobr** [comment]
Fiz um teste no site
https://wiki.addressforall.org/doc/Teste

**Comment by crebollobr** [comment]
Vou fechar essa issue, aparentemente funcionou
