### ISSUE TITLE
Erro mágico em busca por palavra-chave

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/wiki-backup#8]
Provavelmente caiu em uma página danificada do banco, quando buscamos a palavra "endpoint" na Wiki, 

https://wiki.addressforall.org/w/index.php?search=endpoint&title=Especial%3ABusca&wprov=acrw1

**Comment by IgorEliezer** [comment]
"test" também dá erro.

https://wiki.addressforall.org/w/index.php?search=test&title=Especial%3ABusca&wprov=acrw1

**Comment by ppKrauss** [comment]
Sinal que precisamos testar restauro de backup a partir do XML e pasta de imagens... @crebollobr  vai rever, para versão moderna de Mediawiki, o procedimento de backup XML,
https://github.com/AddressForAll/wiki-backup/wiki/Revis%C3%A3o-do-procedimento-de-backup-XML

**Comment by crebollobr** [comment]
Esse problema de erro de busca, não tem log e nem indicação de erro. Criei uma issue sobre isso

**Comment by crebollobr** [comment]
pediram um debug, acabei de enviar

**Comment by crebollobr** [comment]
Era um erro conhecido 
O procedimento é executar o programa  cleanupTitles.php

**Comment by crebollobr** [comment]
Por favor teste o site e feche a issue

**Comment by IgorEliezer** [comment]
Confirmado.
